spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodstall
    username: chetan
    password: chetan
  jpa:
    hibernate:
      ddl-auto: update     
  output:
    ansi:
      enabled: always
   